import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import { JSX } from 'react';
import Profile from '@/components/Profile/profile';
import NavBar from '@/components/navBar';
import Footer from '@/components/footer';

// const geistSans = Geist({
//     variable: '--font-geist-sans',
//     subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//     variable: '--font-geist-mono',
//     subsets: ['latin'],
// });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): JSX.Element {
    return (
        <html lang="en">
            <body className="antialiased">
                <div className="relative">
                    <NavBar></NavBar>
                    <Profile /> {/* ProfileImage handles its own positioning */}
                    <main>{children}</main>
                    <Footer></Footer>
                </div>
            </body>
        </html>
    );
}
